In [2]:
import numpy as np

Задание 5.2  
Вычислите определитель  
$
\begin{pmatrix}
1 & 2 & 3\\
4 & 0 & 6\\
7 & 8 & 9
\end{pmatrix}
$

In [3]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
print(A)
np.linalg.det(A)

[[1 2 3]
 [4 0 6]
 [7 8 9]]


59.999999999999986

Задание 5.3  
1. Вычислите матрицу обратную данной  
$
\begin{pmatrix}
1 & 2 & 3\\
4 & 0 & 6\\
7 & 8 & 9
\end{pmatrix}
$

In [4]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
print(A)
A_inv = np.linalg.inv(A)
A_inv

[[1 2 3]
 [4 0 6]
 [7 8 9]]


array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

5.3
2. Приведите пример матрицы 4х4, ранг которой равен 1

In [5]:
D = np.array([[5, 5, 5, 5], [10, 10, 10, 10], [15, 15, 15, 15], [20, 20, 20, 20]])
print(f'{D}\n{D.shape}')
print(f'Ранг матрицы D равен: {np.linalg.matrix_rank(D, 0.0001)}')

[[ 5  5  5  5]
 [10 10 10 10]
 [15 15 15 15]
 [20 20 20 20]]
(4, 4)
Ранг матрицы D равен: 1


5.4  
Вычислите скалярное произведение двух векторов:
(1, 5) и (2, 8)

In [6]:
a = np.array([1, 5])
b = np.array([2, 8])
print(f'Скалярное произведение векторов {a} и {b}, равно {np.inner(a, b)}')

Скалярное произведение векторов [1 5] и [2 8], равно 42


5.5  
Вычислите смешанное произведение трех векторов:
(1, 5, 0), (2, 8, 7), (7, 1.5, 3)

In [8]:
a = np.array([1, 5, 0])
b = np.array([2, 8, 7])
c = np.array([7, 1.5, 3])
d = np.cross(a, b)
print(f'Смешанное произведение трех векторов равно: {np.inner(d, c)}')

Смешанное произведение трех векторов равно: 228.5
